  <div class="slider-wrapper theme-default asyn-wrap" id="slider">
    <div class="my_asyncslider">
	
     
	  <div id="slide-01">
           <div class="bannerimg"> <img src="images/img3.png" alt="" /> </div>
		   <div class="description">
          <h1 class="welcome">Pick: Responsive Theme <br>
Perfect Bussines and Creative Theme</h1>
          <p>Curabitur nec libero felis, ac egestas quam. Suspendisse potentia. Doneca a molestiean ante. Sed magna lectus, mollis at porta ac, pharetra in quam id tempor vel metus.</p>
          <div class="viewPro"> <a href="#" class="btn">Learn More</a> </div>
        </div>
      </div>
	  <div id="slide-02">
        <div class="description">
          <h1 class="welcome">You can embed video from Vimeo<br>
and Youtube :)</h1>
          <p>Curabitur nec libero felis, ac egestas quam. Suspendisse potentia. Doneca a molestiean ante. Sed magna lectus, mollis at porta ac, pharetra in quam id tempor vel metus.</p>
          <div class="viewPro"> <a href="#" class="btn">Learn More</a> </div>
        </div>
        <div class="bannerimg"> <iframe src="http://player.vimeo.com/video/25541923?color=c9161f" width="330" height="230" ></iframe></div>
      </div>
      <div id="slide-03">
        <div class="description">
          <h1 class="welcome">The beautyful slider with different<br>
animation and option!</h1>
          <p>Curabitur nec libero felis, ac egestas quam. Suspendisse potentia. Doneca a molestiean ante. Sed magna lectus, mollis at porta ac, pharetra in quam id tempor vel metus.</p>
          <div class="viewPro"> <a href="#" class="btn">Learn More</a> </div>
        </div>
        <div class="bannerimg"> <img src="images/img5.png" alt="" width="347" height="312" /> </div>
      </div>
      
      
    </div>
    
    
    
  </div>
  <fieldset id="center_wrapper">
  <div id="body_wrapper">
    <div class="body_heading">
      <div class="heading_intro">
        <h2><a href="#">We are pick</a></h2>
        <p>Super awesome creative agency New York based</p>
      </div>
      <div class="right_button_holder"><a href="#" class="button_head">Contact Us</a></div>
    </div>
    <div class="body_contant">
      <div class="top_container">
        <div class="one_third box">
          <div class="box_heading"><img src="images/box1.png" alt="" />
            <h3><a href="#">Responsive Template</a></h3>
          </div>
          <p>Cum sociis natoque petibus et magnis dis parturient montes,  Doles sociis natoque penus et magnis dis  parturient montes, nascetur ridiculus mus.  Cum sociis natoque penatibus et magnis dis parturient. </p>
          <div class="read_more_button"><a class="button" href="#">Learn More</a></div>
        </div>
        <div class="one_third box">
          <div class="box_heading"><img src="images/box2.png" alt=""/>
            <h3><a href="#">modern & clean design</a></h3>
          </div>
          <p>Cum sociis natoque petibus et magnis dis parturient montes,  Doles sociis natoque penus et magnis dis  parturient montes, nascetur ridiculus mus.  Cum sociis natoque penatibus et magnis dis parturient. </p>
          <div class="read_more_button"><a class="button" href="#">Learn More</a></div>
        </div>
        <div class="one_third column-last box">
          <div class="box_heading"><img src="images/box3.png" alt=""/>
            <h3><a href="#">very flexible</a></h3>
          </div>
          <p>Cum sociis natoque petibus et magnis dis parturient montes,  Doles sociis natoque penus et magnis dis  parturient montes, nascetur ridiculus mus.  Cum sociis natoque penatibus et magnis dis parturient. </p>
          <div class="read_more_button"><a class="button" href="#">Learn More</a></div>
        </div>
        <div class="one_third box">
          <div class="box_heading"><img src="images/box4.png" alt="" />
            <h3><a href="#">Easy to Customize</a></h3>
          </div>
          <p>Cum sociis natoque petibus et magnis dis parturient montes,  Doles sociis natoque penus et magnis dis  parturient montes, nascetur ridiculus mus.  Cum sociis natoque penatibus et magnis dis parturient. </p>
          <div class="read_more_button"><a class="button" href="#">Learn More</a></div>
        </div>
        <div class="one_third box">
          <div class="box_heading"><img src="images/box5.png" alt=""/>
            <h3><a href="#">Great support</a></h3>
          </div>
          <p>Cum sociis natoque petibus et magnis dis parturient montes,  Doles sociis natoque penus et magnis dis  parturient montes, nascetur ridiculus mus.  Cum sociis natoque penatibus et magnis dis parturient. </p>
          <div class="read_more_button"><a class="button" href="#">Learn More</a></div>
        </div>
        <div class="one_third column-last box">
          <div class="box_heading"><img src="images/box6.png" alt=""/>
            <h3><a href="#">Very first theme</a></h3>
          </div>
          <p>Cum sociis natoque petibus et magnis dis parturient montes,  Doles sociis natoque penus et magnis dis  parturient montes, nascetur ridiculus mus.  Cum sociis natoque penatibus et magnis dis parturient. </p>
          <div class="read_more_button"><a class="button" href="#">Learn More</a></div>
        </div>
      </div>
      <div class="divider">
        <div class="divider_text">
          <h2 class="marnone">Latest Project of our work <span><a href="#">Go to portfolio!</a> </span></h2>
        </div>
        
      </div>
      <div class="latest_products">
        <ul class="portfolio_contain gallery">
          <li data-id="id-1" data-type="interface" class="main one_fourth">
            <div class="project_box">
              <div class="rounded_image"> <img src="images/port1.png"  class="squared_img" alt="" /> <div class="holygen"> </div></div>
              <div class="line"></div>
              <div class="project_description">
                <h2><a href="#">Dee Pee</a></h2>
                <p>Cum sociis natoque penatibus et 
                  magnis dis parturient montes, 
                  nascetur ridiculus mus. </p>
              </div>
              <div class="button_holder"><a href="#" class="button">Read More</a></div>
            </div>
          </li>
          <li data-id="id-2" data-type="webdesign" class="main one_fourth">
            <div class="project_box">
              <div class="rounded_image"> <img src="images/port2.png"  class="squared_img" alt=""/><div class="holygen"> </div> </div>
              <div class="line"></div>
              <div class="project_description">
                <h2><a href="#">Enjoy the silence</a></h2>
                <p>Cum sociis natoque penatibus et 
                  magnis dis parturient montes, 
                  nascetur ridiculus mus. </p>
              </div>
              <div class="button_holder"><a href="#" class="button">Read More</a></div>
            </div>
          </li>
          <li data-id="id-3" data-type="ecommerce" class="main one_fourth ">
            <div class="project_box">
              <div class="rounded_image"> <img src="images/port3.png"  class="squared_img" alt=""/> <div class="holygen"> </div></div>
              <div class="line"></div>
              <div class="project_description">
                <h2><a href="#">Wasteland Cruizer</a></h2>
                <p>Cum sociis natoque penatibus et 
                  magnis dis parturient montes, 
                  nascetur ridiculus mus. </p>
              </div>
              <div class="button_holder"><a href="#" class="button">Read More</a></div>
            </div>
          </li>
          <li data-id="id-4" data-type="advertisement" class="main one_fourth last">
            <div class="project_box">
              <div class="rounded_image"> <img src="images/port4.png"  class="squared_img" alt=""/> <div class="holygen"> </div></div>
              <div class="line"></div>
              <div class="project_description">
                <h2><a href="#">Survivalism</a></h2>
                <p>Cum sociis natoque penatibus et 
                  magnis dis parturient montes, 
                  nascetur ridiculus mus. </p>
              </div>
              <div class="button_holder"><a href="#" class="button">Read More</a></div>
            </div>
          </li>
        </ul>
      </div>
      <div class="divider">
        <div class="divider_text">
          <h2>Latest Post from the Blog<span><a href="#">View More!</a> </span></h2>
        </div>
        
      </div>
      <div class="latest_posts">
        <div class="one_fourth project_box">
          <div class="tumbnail-post">
            <div class="tumbnail_post_pic">
              <div class="kreis"> </div>
              <img src="images/fromblog2.png" alt=""> </div>
          </div>
          
          <div class="project_description">
            <h2><a href="#">Impossible</a></h2>
            <p>Cum sociis natoque penatibus et 
              magnis dis parturient montes, 
              nascetur ridiculus mus. </p>
          </div>
          <div class="button_holder"><a href="#" class="button">Read More</a></div>
        </div>
        <div class="one_fourth project_box">
          <div class="tumbnail-post">
            <div class="tumbnail_post_pic">
              <div class="kreis"> </div>
              <img src="images/fromblog3.png" alt=""> </div>
          </div>
          
          <div class="project_description">
            <h2><a href="#">A new dawn</a></h2>
            <p>Cum sociis natoque penatibus et 
              magnis dis parturient montes, 
              nascetur ridiculus mus. </p>
          </div>
          <div class="button_holder"><a href="#" class="button">Read More</a></div>
        </div>
        <div class="one_fourth project_box">
          <div class="tumbnail-post">
            <div class="tumbnail_post_pic">
              <div class="kreis"> </div>
              <img src="images/fromblog4.png" alt=""> </div>
          </div>
          
          <div class="project_description">
            <h2><a href="#">Natur formen</a></h2>
            <p>Cum sociis natoque penatibus et 
              magnis dis parturient montes, 
              nascetur ridiculus mus. </p>
          </div>
          <div class="button_holder"><a href="#" class="button">Read More</a></div>
        </div>
        <div class="one_fourth project_box column-last">
          <div class="tumbnail-post">
            <div class="tumbnail_post_pic">
              <div class="kreis"> </div>
              <img src="images/fromblog1.png" alt=""> </div>
          </div>
          
          <div class="project_description">
            <h2><a href="#">most wanted</a></h2>
            <p>Cum sociis natoque penatibus et 
              magnis dis parturient montes, 
              nascetur ridiculus mus. </p>
          </div>
          <div class="button_holder"><a href="#" class="button">Read More</a></div>
        </div>
      </div>
      <div class="bottom_wrapper">
        <div class="one_fourth choose">
          <div class="bottom_wrapper_heading">
            <div class="divider_text">
              <h2 class="marnone">WHY CHOOSE US?</h2>
            </div>
            <div class="line_min1"></div>
          </div>
          <div id="accordion">
            <h3><a href="#">Business Interactive</a></h3>
            <div>
              <p> Cum sociis natoque penatibus 
                Doles sociis natoque montes.</p>
            </div>
            <h3><a href="#">Testing Mind</a></h3>
            <div>
              <p> Cum sociis natoque penatibus 
                Doles sociis natoque montes.</p>
            </div>
            <h3><a href="#">Analytics & measurement</a></h3>
            <div>
              <p> Cum sociis natoque penatibus 
                Doles sociis natoque montes.</p>
            </div>
            <h3><a href="#">Consumer Research</a></h3>
            <div>
              <p> Cum sociis natoque penatibus 
                Doles sociis natoque montes.</p>
            </div>
            <h3><a href="#">Prototyping</a></h3>
            <div>
              <p> Cum sociis natoque penatibus 
                Doles sociis natoque montes.</p>
            </div>
            <h3><a href="#">Lorem Ispum</a></h3>
            <div>
              <p> Cum sociis natoque penatibus 
                Doles sociis natoque montes.</p>
            </div>
          </div>
        </div>
        <div class="one_half w100">
          <div class="bottom_wrapper_heading">
            <div class="divider_text">
              <h2 class="marnone">Our Clients</h2>
            </div>
            <div class="line_min1"></div>
          </div>
          <ul class="client">
            <li><a href="#" class="client1"></a> </li>
            <li><a href="#" class="client2"></a> </li>
            <li><a href="#" class="client3"></a> </li>
            <li><a href="#" class="client4"></a> </li>
            <li><a href="#" class="client5"></a> </li>
            <li><a href="#" class="client6"></a> </li>
          </ul>
        </div>
        <div class="one_fourth column-last">
          <div class="bottom_wrapper_heading">
            <div class="divider_text">
              <h2 class="marnone">TESTIMONIALS</h2>
            </div>
            <div class="line_min1"></div>
          </div>
          <div class="contant_right">
            <div class="intro">
              <div class="details"><img src="images/quotes.png" alt=""/> Lorem ipsum dolor sit amet, consetet
                edolor sit amet. Lorem ipsum dolor sit amet, 
                consetetur sadipscing elitr, sed diam nonumy
                tempor invidunt ut labore et dolore magna. </div>
              <div class="name"><a>John Doe</a>(Java Developer)</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </fieldset>